version: '3.8'

services:
  tm-app:
    build: .
    ports:
      - "9998:9998"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 