apiVersion: v1
kind: ConfigMap
metadata:
  name: tm-app-config
data:
  application-prod.properties: |
    # 应用配置
    spring.application.name=tm-app
    server.port=8080
    
    # 缓存配置
    spring.cache.type=caffeine
    spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=3600s
    
    # 日志配置
    logging.level.root=INFO
    logging.level.com.hsbc.tm=INFO
    
    # Actuator配置
    management.endpoints.web.exposure.include=health,info,metrics
    management.endpoint.health.show-details=always 