apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - configmap.yaml

namePrefix: tm-

images:
- name: ${DOCKER_REGISTRY}/tm-app
  newName: ${DOCKER_REGISTRY}/tm-app
  newTag: latest

configMapGenerator:
- name: tm-app-config
  files:
  - application-prod.properties 